### ISSUE TITLE
Violin plots no longer displaying

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#120]
The code to decide between the violin plots and the density relied on the draws being present in only one. Currently only produces a density (not sure why the test didn't fail?)

- Make a test for this to catch next time
- Fix the code so it produces violin plots for SAEs

**Comment by jgabry** [comment]
Yeah I wonder why the visual test didn't fail. I can look into that.

**Comment by jgabry** [comment]
Oh nevermind, I see what you mean. I agree that it's broken, but the reason the tests didn't fail is that the test was using a fake data frame (that still had the "draw" column) instead of actual output from aggregate. To test the plot appearance we needed deterministic output so I didn't use `population_predict` -> `aggregate`.

**Comment by jgabry** [comment]
I can fix this issue
