### ISSUE TITLE
Failed to plot the estimation with CCES/ACS data

### ISSUE THREAD

**Issue by Dewi-Amaliah** [lauken13/mrpkit#124]
When running `fit1$plot(popn_estimation)`

I got this error 

``` r
Error in `[.data.frame`(fit_obj$map()$sample()$survey_data(), c(outcome,  : 
  undefined columns selected
```
The traceback is: 

``` r
9. stop("undefined columns selected")
8. `[.data.frame`(fit_obj$map()$sample()$survey_data(), c(outcome, ".key")) at misc.R#43
7. fit_obj$map()$sample()$survey_data()[c(outcome, ".key")] at misc.R#43
6. as.data.frame(y)
5. nrow(y <- as.data.frame(y))
4. merge.data.frame(fit_obj$map()$mapped_sample_data(), fit_obj$map()$sample()$survey_data()[c(outcome, ".key")], by = ".key")
3. merge(fit_obj$map()$mapped_sample_data(), fit_obj$map()$sample()$survey_data()[c(outcome, ".key")], by = ".key") at misc.R#43
2. create_wtd_ests(self, lhs_var)
1. fit1$plot(popn_estimation)
```

**Comment by lauken13** [comment]
Hi folks,

I think the issue here is that the different fit objects have different storage of the original data. In some places we can avoid this by referring to the original map objects, but we do need access to the formula after the fit stage. 

For example:

- To access the formula from rstanarm, we use fit_obj$.__enclos_env__$private$fit_$formula
- To access the formula from a lme4 object, we use attributes(private$fit_@frame)$formula

For most of the post processing munging we need the formula because we need to identify the outcome variable and it's not contained included anywhere else.  

@jgabry, @Dewi-Amaliah, @RohanAlexander  probably good for us all to be in the loop on this, but @jgabry  I think this would involve changing the fit method that you wrote. What do you think? 

Lauren

**Comment by lauken13** [comment]
So if you're okay with this, here's my todo to fix

- Add a formula slot to the fit object (suggest `formula_`) to match the `fit_`
- Change the tests so that the plots are tested for all model fits (not just one). This is why we didn't pick it up
- Change code after fit to use this new formula location rather than pulling from the fit_ object

I suggest that I roll this into the current branch that I am working on (add_summary) as it has substantial changes to the plot function anyway.

**Comment by Dewi-Amaliah** [comment]
Hi @lauken13,

That sounds good to me.

**Comment by jgabry** [comment]
@lauken13 sorry I missed this sooner. This sounds ok to me. Thanks for working on it!

**Comment by jgabry** [comment]
> * To access the formula from rstanarm, we use fit_obj$.**enclos_env**$private$fit_$formula

For this I would just use `fit_obj$fit()$formula`. I don't think there's even a need to directly use `$.**enclos_env**`, although I could be wrong. But in this case you can just call the `fit()` method to get the fitted model object.

**Comment by jgabry** [comment]
> I don't think there's even a need to directly use `$.**enclos_env**`

oops I meant "ever a need"
